name: Continuous Delivery & Deployment

on:
  push:
    branches:
      - master   # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ (Test?) Build & Package the code for production
      - name: Build Angular for production
        run: |
          ng build --prod

      # 3️⃣ Build Docker image using the premade Dockerfile
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-client:latest .

      # 4️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 5️⃣ Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-client:latest

      # 6️⃣ SSH into droplet and update k3s deployment
      - name: Deploy to k3s
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            kubectl set image deployment/portfolio-client portfolio-client=${{ secrets.DOCKERHUB_USERNAME }}/portfolio-client:latest -n default
            kubectl rollout status deployment/portfolio-client -n default
